### PR TITLE
Fix dub.json file

### PR DESCRIPTION
**Pull request by cschlote**
Just fixing the dub.json file. dmpp can now be build with dmd, ldc2, gdc and latest beta of dmd.

### CODE REVIEW

**Comment by schveiguy** [comment]
Oof, just made almost the same PR lol.

**Comment by cschlote** [comment]
I really like to contribute because D is a very cool language. But it is very disappointing, if even such simple things won't make it into the source after weeks or even months. It feels like being ignored. Or even more like riding a dead horse. The most people would feel so, stop contributing and move to some other project like Rust et al..  Maybe this is one of the reasons, why D isn't very popular?

**Comment by schveiguy** [comment]
This project isn't a major D project, I'm sure @WalterBright will get around to merging one of these. You just gotta keep pinging him.

I'm planning on utilizing this code for my own purposes, I just saw the dub build was easily fixed. At first, I thought I had to download dmd and put it in myself!

**Comment by WalterBright** [comment]
Sorry, I hadn't noticed the PR before.

**Comment by cschlote** [comment]
Thanks!

**Pull request merged**
